# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18z7K6AUf87pKsUbhCPC6COTtlDmUWsfD
"""

def time_to_seconds(time_str):
    hours, minutes, seconds = map(int, time_str.split(':'))
    return hours * 3600 + minutes * 60 + seconds

def is_present(attendedtime,total):
  percent = (attendedtime/total)*100
  if(percent>=85):
    return True
  else:
    return False

from datetime import datetime
import pandas as pd
count=0
student_list = pd.read_csv("2025-rollno.s-AI.csv")
df = pd.read_csv("5-9-2024.csv", skiprows=4)
df1 = pd.read_csv("5-9-2024.csv", nrows=4,header=None)
present = []
start = str(df1.iloc[2])
end = str(df1.iloc[3])
start=start[:len(start)-23].split()[5]
end=end[:len(end)-23].split()[5]

time1 = datetime.strptime(start, '%H:%M:%S')
time2 = datetime.strptime(end, '%H:%M:%S')

time_gap = time2 - time1

time_gap = time_gap.total_seconds()
print("Time gap:", time_gap)

for i in range(len(df)):
    value = df.loc[i, "Time in Call"]
    value = time_to_seconds(value)
    if(is_present(value,time_gap)):
      # print(df.loc[i,"Full Name"])
      df.loc[i,"status"]="Present"
      present.append(df.loc[i,"Full Name"])
    else:
      df.loc[i,"status"]="Not present"

for i in range(len(student_list["Student Name"])):
  if student_list.loc[i,"Student Name"] in present:
    student_list.loc[i,"status"]="Present"
  else:
    student_list.loc[i,"status"]="Not Present"

print(student_list)
print("Total student count = ",len(df))
print("presented students count =",len(student_list))
student_list.to_csv("attended_students.csv", index=False)

